name: Hillel Auto e2e tests
on: workflow_dispatch

jobs:
  cypress_run1:
    runs-on: ubuntu-latest
    steps:
      - name: Get project files
        uses: actions/checkout@v4
      - name: Install all dependencies
        run: npm install
      - name: Run tests
        run: npm run cy:run
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  cypress_run2:
    runs-on: ubuntu-latest
    steps:
      - name: Get project files
        uses: actions/checkout@v4
      - name: Install all dependencies
        run: npm install
      - name: Run tests
        run: npm run cy:run
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
